FROM polyaxon/polyaxon-examples

RUN apt-get install -y vim
RUN pip3.6 uninstall -y tensorflow 
RUN pip3.6 install tensorflow===1.5.0  -i https://pypi.doubanio.com/simple
COPY tensorflow_distributed_example /tensorflow_distributed_example
